### PR TITLE
cleaning printfs and error handling

### PR DESCRIPTION
**Pull request by basegpu**
In `op_hdf5.c` there were inconsistencies how to print log information and how to handle errors.

* replacing all `printf(...)` with `op_printf(...)`.
* replacing all `return NULL` with `exit(2)`.
* put some `if (OP_diags > ...) {}`around log-prints`.

The last point helped in getting nicer log-files when fetching `op_dat` directly to h5-container.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Thanks for this. Looks mostly ok. 
Two issues:
(1) Could you elaborate on point 3 above. 
I think we would like to have the prints that you have put `if (OP_diags > ...) {}` around. I think it helps to know that when for example you are dumping op_dats to an HDF5 file something have happened, rather than silently writing a file (if OP_diags have not been set to a value more than 1, which is what we do for performance runs). 

(2) The changes that you have done needs to be done also in op_mpi_hdf5.c 

Thanks.

**Comment by reguly** [comment]
Some 'return NULL' statements are intentional - we can allow failing to load some datasets - this is actually being relied on in some codes for checking whether certain variables are present.

**Comment by basegpu** [comment]
ok, I see, thx for your feedbacks.

Improvements are as follows:

* The `return NULL` statements are prepended with `H5Fclose(file_id)`.
* The `return NULL` statements are called whenever `H5Dopen(file_id, name, H5P_DEFAULT) < 0`.
* For all other error checks `exit(2)` is called.
* Three different levels of log information:
  - in case of error: regular `op_printf(...)`
  - at beginning of writing function: regular `op_printf(...)`
  - other/additional information: `if (OP_diags > 3) op_printf(...)`
* The same is applied to `op_mpi_hdf5.c` as well, but calling `MPI_Abort(OP_MPI_HDF5_WORLD, 2)` instead of `exit(2)`.

**Comment by gihanmudalige** [comment]
Thanks. I will run the tests and see if anything is broken. But @reguly  can you also have a look.

**Comment by gihanmudalige** [comment]
Ok .. I got all the tests to pass. Merging now.

**Comment by basegpu** [comment]
thx for the review!

**Pull request merged**
