### PR TITLE
Add variadic op_par_loop implementation.

### PR DESCRIPTION
**Pull request by bgd54**
Using variadic templates in theory enable par_loops with more than 20 parameters.
To call the kernel function we need a set of indices as template parameters so we can use template expansion indexing the p_a array. This requires a wrapper call around the op_par_loop implementation to build the index sequence from 0 to sizeof...(# of arguments). 
The drawback of the index sequence and the OPARG variadic template arg is the unreadable function name for op_par_loop_impl (something like op_par_loop_impl<double, int, ... op_arg, op_arg, op_arg ...., 0,1,2,3...>). The index generation is implemented after c++14. I've added a short workaround for c++11 as well.

I haven't tested the implementation on vectorized parameters, just on a set of simple direct and indirect kernels with reductions. But after the template expansions the resulting code should be the same as before.. I hope.

### CODE REVIEW

**Comment by reguly** [comment]
Does seem to work with vectorised args too. Please do include a fallback path for earlier than C++11 (by keeping the original)

**Comment by gihanmudalige** [comment]
Yes, icpc -std=c++11 fixes this. We will need a fallback.

**Comment by bgd54** [comment]
The fallback is ready for pre c++11 with the same #if __cplusplus >= 201103L ... construct used for c++14 and std::index_sequence. It works for my testcases with -std=c++03 and c++98.

**Comment by gihanmudalige** [comment]
All tests passed. Good to merge

**Pull request merged**
