### PR TITLE
feature/python translator

### PR DESCRIPTION
**Pull request by basegpu**
This pull request contributes to more flexibility in the OP2 building process by updating the python translator:

- the functionality and behaviour of the translator did not change when applied as before (backward compatibility).
- NEW: in addition to the source files, directories can be provided to the translator as well. These directories are then used as look up directories for user kernel header files (having the same name as the kernel function). e.g.

~~~bash
python op2.py file1.cpp file2.cpp userKernels
~~~

- NEW: an optional (C-style) flag `-o` can be used to define the number of threads shall be used in case of OpenMP backend. If not defined, the number of threads is `omp_get_max_threads()` per default. If an integer is provided, the number of cores is set by `omp_set_num_threads(...)`. If a string is provided, it is used as runtime variable name to define the number of cores. e.g.

~~~bash
python op2.py -o op_global_nThreads file1.cpp file2.cpp
~~~

- two improved minor issues/bugfixes

### CODE REVIEW

**Comment by reguly** [comment]
This is very good stuff! As for the OpenMP number of threads: is there a reason why the OMP_NUM_THREADS environment variable (set at runtime instead of compile time) is not sufficient for this? This way you would be hardcoding the number of threads into the code itself - currently it just automatically uses as many threads as many cores there are in the system.

**Comment by basegpu** [comment]
I agree, in case of a specific number of threads, setting the environment variable `OMP_NUM_THREADS` is more appropriate then setting it at compile time. But then we should call `omp_get_num_threads()` instead of `omp_get_max_threads()` inside the kernels, right?

To fully circumvent the translator, one could therefore call anywhere in the code e.g. `putenv("OMP_NUM_THREADS=4")` from `stdlib.h` to set the number of threads at runtime in a nice way, ok?

This way we could omit the OpenMP changes...

**Comment by reguly** [comment]
omp_get_max_threads() will return whatever was set to OMP_NUM_THREADS. That call can be used outside of an OpenMP region. omp_get_num_threads() is used inside an OpenMP parallel region, and tells you how many threads are running in that region currently.
Yes, putenv is the appropriate programmatic way to set this - I would advise doing it this way.

**Comment by basegpu** [comment]
ok, I will do an update according to this.

**Comment by basegpu** [comment]
done.

the indentation commit in `op2.py` (1a4150a) is unfortunate. The indent was of size 4, and I thought this was me, then I changed it to the correct size of 2 (as in the other files). Now I saw in the diff that originally it was 4 and in this pull request it will be 2. The comparison of `op2.py` is somewhat difficult now...

**Comment by reguly** [comment]
Looks good to me. @gihanmudalige please run the usual tests.

**Comment by gihanmudalige** [comment]
ok will do so now

**Comment by gihanmudalige** [comment]
Ok .. may be the tests need updating but doing code gen with the following does not work:
~/OP2-GIT/OP2-Common/apps/c/airfoil/airfoil_hdf5/dp$ ../../../../../translator/c/python/op2.py airfoil.cpp

**Comment by basegpu** [comment]
I confirm this issue. this is strange, actually all applications should run without changes... I have a look!

**Comment by basegpu** [comment]
found the bug. could you please run the tests?
or is there an easy way to run the tests by myself?

**Comment by gihanmudalige** [comment]
Thanks. I am doing them now.

**Comment by gihanmudalige** [comment]
The tests are actually in /scripts/test_makefiles.sh
But there are hardcoded values in that for our test system at Oxford. However these should be easily setup if you want to do the tests in your system.

**Comment by basegpu** [comment]
@reguly : I am not able to set `OMP_NUM_THREADS` via `putenv(char*)` at runtime. `omp_get_max_threads()` always returns the number of threads available on the system, or the value from the environment, set before calling the executable...

>omp_get_max_threads() will return whatever was set to OMP_NUM_THREADS. That call can be used outside of an OpenMP region. omp_get_num_threads() is used inside an OpenMP parallel region, and tells you how many threads are running in that region currently.
Yes, putenv is the appropriate programmatic way to set this - I would advise doing it this way.

Is there a trick how to set the number of threads programmatically?

**Comment by aowenson** [comment]
Use the following two lines of code, outside of a parallel region, to set the number of threads spawned by all subsequent parallel regions:

```
omp_set_num_threads(desired_num_threads);
omp_set_dynamic(0);
```

**Comment by basegpu** [comment]
no further commits.
setting the number of OpenMP threads outside of op2 worked!

**Pull request merged**
