### PR TITLE
Feature/timing enhanced

### PR DESCRIPTION
**Pull request by aowenson**
This branch has been pruned of other branches that were merged in.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Thanks. Running tests now.

**Comment by gihanmudalige** [comment]
I have done the tests on Octon .. all seems to pass. @reguly  would be good to have your review on this. This branch is good to be merged in to master as its required by Andrew's MG-CFD miniapp (i.e. the RR miniapp).

**Comment by reguly** [comment]
Has this been rebased on master?

Please remove the declaration of inner_cpu_t1 and other variables from the generated code unless they are used.

**Comment by gihanmudalige** [comment]
@aowenson  ... we should resolve these conflicts.

**Comment by aowenson** [comment]
I am looking into it, Git is doing odd things to this branch.

**Comment by aowenson** [comment]
The "conflicts" were additions that the branch would insert into master without any overwriting, I don't understand why Git flagged those up. Not the first time I have seen this happen.

@reguly, rather than rebase I have been merging in master.

**Comment by gihanmudalige** [comment]
ok, let me run the tests again, just in case things have diverged.

**Comment by aowenson** [comment]
@gihanmudalige You will have to restart testing, I noticed that Git had removed my changes to op_lib_core.h. Now restored.

**Comment by gihanmudalige** [comment]
I have not started yet. So its fine.

**Comment by aowenson** [comment]
Continue to pause testing, there are more missing changes.

**Comment by aowenson** [comment]
@gihan You can unpause the testing now.

**Comment by gihanmudalige** [comment]
@aowenson Thanks for this. Probably more work for you than necessary !
I have just started the tests again.

**Comment by gihanmudalige** [comment]
@reguly , if you are ok, then these are ready to go.

**Pull request merged**
