### PR TITLE
Feature/c arg opt

### PR DESCRIPTION
**Pull request by reguly**
This pulls in optional argument support for the C side.

Gihan please run the usual tests for this

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Are there tests in here for the new feature ? I cannot remember if we had an application already.

**Comment by reguly** [comment]
There aren’t any. For my own testing, I modified jac and aero - perhaps I can push that in too...

**Comment by gihanmudalige** [comment]
Either Aero or Jac will do, let me know, so that I can add tests to the main test script.

**Comment by basegpu** [comment]
I encountered additional issues concerning the optional args:

Having the kernel
~~~C
op_par_loop(kernel_MORPHOLOGY_FixedBedCorrection, "fixedBed", theSet,
            op_opt_arg_dat( flag, dat1, 0, map1, 1, "int", OP_READ ),
            op_opt_arg_dat( flag, dat2, -3, map2, 1, "int", OP_READ ),
            op_arg_gbl( &g1, 1, "double", OP_READ ),
            op_arg_dat( dat3, 0, map1, 1, "double", OP_READ ),
            op_arg_dat( dat4, 0, map1, 1, "double", OP_READ ),
            op_arg_dat( dat5, -1, OP_ID, 1, "double", OP_READ ),
            op_arg_dat( dat6, 0, map1, 3, "int", OP_READ ),
            op_arg_dat( dat7, -3, map2, 1, "double", OP_READ ),
            op_arg_dat( dat8, -3, map2, 1, "double", OP_RW ),
            op_arg_gbl( &g2, 1, "double", OP_MAX )
        );
~~~

1. compile errors for sequential backend (`op_gen_seq.py`):
`... ‘arg2’ was not declared in this scope ...`
`... ‘arg3’ was not declared in this scope ...`
The errors occur in the update of kernel records. I guess args 2 and 3 should represent the vectorised data of arg1? something went wrong here...
~~~cuda
  if (arg0.opt) {
    OP_kernels[19].transfer += (float)set->size * arg0.size;
  }
  if (arg1.opt) {
    OP_kernels[19].transfer += (float)set->size * arg1.size;
  }
  if (arg2.opt) {
    OP_kernels[19].transfer += (float)set->size * arg5.size;
  }
  if (arg3.opt) {
    OP_kernels[19].transfer += (float)set->size * arg6.size;
  }
~~~

2. compile warnings for cuda backend (`op_gen_cuda_simple.py`):
`... variable "map0idx" was declared but never referenced ...`
It might be linked to a map that is used for both an optional arguments and non-optional ones? In this specific case the map idx are still correct...but it is somehow confusing and might be a potential source of errors.
~~~cuda
  //initialise local variables
  if (optflags & 1<<0) {
    int map0idx = opDat0Map[n + set_size * 0];
  }
  if (optflags & 1<<1) {
    int map1idx = opDat1Map[n + set_size * 0];
  }
  if (optflags & 1<<1) {
    int map2idx = opDat1Map[n + set_size * 1];
  }
  if (optflags & 1<<1) {
    int map3idx = opDat1Map[n + set_size * 2];
  }
  int map0idx = opDat0Map[n + set_size * 0];
  int map1idx = opDat1Map[n + set_size * 0];
  int map2idx = opDat1Map[n + set_size * 1];
  int map3idx = opDat1Map[n + set_size * 2];
~~~

**Comment by reguly** [comment]
I have pushed a quick fix for the 1st issue. The 2nd issue will not affect your results and correctness, but will fix that too

**Comment by gihanmudalige** [comment]
Have been running tests on this. I am getting the following error with clang compilers building openmp4 
make aero_openmp4
..
..
..
clang++  -O3  -I/home/mgiles/ireguly/llvm/build/lib/../tools/openmp/runtime/src/ -fopenmp=libomp -Rpass-analysis -I/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/include -I/opt/hdf5-gnu/include \
                -Iopenmp4 -I. -c openmp4/aero_omp4kernels.cpp -o openmp4/aero_omp4kernels.o
In file included from openmp4/aero_omp4kernels.cpp:9:
openmp4/res_calc_omp4kernel.cpp:119:21: error: use of undeclared identifier 'arg'
    int dat8size = (arg.opt?1:0) * getSetSizeFromOpArg(&arg8) * arg8.dat->dim;
                    ^
openmp4/res_calc_omp4kernel.cpp:125:21: error: use of undeclared identifier 'arg'
    int dat9size = (arg.opt?1:0) * getSetSizeFromOpArg(&arg9) * arg9.dat->dim;
                    ^
openmp4/res_calc_omp4kernel.cpp:127:22: error: use of undeclared identifier 'arg'
    int dat13size = (arg.opt?1:0) * getSetSizeFromOpArg(&arg13) * arg13.dat->dim;
                     ^
3 errors generated.
make: *** [aero_openmp4] Error 1

**Comment by basegpu** [comment]
thx for the fixes. it compiles now, sequential and openmp runs as expected.

but there seem to be major problems now for the cuda backend (`op_gen_cuda_simple.py`). the code gives wrong results. It might be related to a compile warning in kernels that have ONLY indirect data (no direct ones)
~~~
warning: variable "offset_b" was set but never used
~~~

**Comment by reguly** [comment]
Ah, sloppy testing on my part. Fixed the CUDA and OpenMP4 issue.

**Comment by basegpu** [comment]
perfect, now all our tests on `seq`, `openmp`, and `cuda` backends pass.

**Comment by reguly** [comment]
@gihanmudalige - please run the usual tests

**Comment by gihanmudalige** [comment]
Already running !

**Comment by gihanmudalige** [comment]
Not sure if this is an issue with my system. But I am still getting the following:

clang++  -O3  -I/home/mgiles/ireguly/llvm/build/lib/../tools/openmp/runtime/src/ -fopenmp=libomp -Rpass-analysis -I/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/include -I/opt/hdf5-gnu/include \
		-Iopenmp4 -I. -c openmp4/aero_omp4kernels.cpp -o openmp4/aero_omp4kernels.o
In file included from openmp4/aero_omp4kernels.cpp:9:
openmp4/res_calc_omp4kernel.cpp:125:21: error: use of undeclared identifier 'arg'
    int dat9size = (arg.opt?1:0) * getSetSizeFromOpArg(&arg9) * arg9.dat->dim;
                    ^
openmp4/res_calc_omp4kernel.cpp:127:22: error: use of undeclared identifier 'arg'
    int dat13size = (arg.opt?1:0) * getSetSizeFromOpArg(&arg13) * arg13.dat->dim;

**Comment by reguly** [comment]
It’s not - I have pushed a fix for this

**Comment by gihanmudalige** [comment]
OK all tests passed !

**Pull request merged**
