### PR TITLE
Type conversions allowed

### PR DESCRIPTION
**Pull request by reguly**
When reading datasets

### CODE REVIEW

**Comment by gihanmudalige** [comment]
running tests now

**Comment by gihanmudalige** [comment]
Current tests passed !
Do we want to add a test that evaluates whether the type conversion works correctly ?

**Comment by reguly** [comment]
Could you help with that please? I added a test for Airfoil HDF5 SP, but I am not sure how you get the HDF5 file itself - basically the test would simply read the HDF5 file which contains the double precision values in the SP application as well.

**Comment by gihanmudalige** [comment]
Ok I will add the tests

**Comment by gihanmudalige** [comment]
Added tests and all tests passed

**Pull request merged**
