### PR TITLE
Fix/python translator

### PR DESCRIPTION
**Pull request by aowenson**
These are translator changes needed to translate the latest version of MG-CFD. However not urgent to merge as the MG-CFD repository contains the OP2-generated files.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
I will run the usual tests.

**Comment by aowenson** [comment]
I have fixed the compile error relating to aero OpenMP4. The same issue was present in OpenACC, also fixed.

**Comment by aowenson** [comment]
Lots of commits today, most are recommits of earlier work that appears to have disappeared from Git. 

There are 2 genuinely new commits, named "Tentative bugfix for ... ". They address some compilation errors of the SIMD variant of MG-CFD-app-OP2, but others errors remain so I cannot test these fixes.

**Comment by gihanmudalige** [comment]
There is an issue when parsing aero.cpp in aero_hdf5/dp  for the vec code generator.

**Comment by gihanmudalige** [comment]
File "../../../../../translator/c/python/op2.py", line 953, in <module>
    main(srcFilesAndDirs=args)
  File "../../../../../translator/c/python/op2.py", line 921, in main
    op2_gen_mpi_vec(masterFile, date, consts, kernels) # MPI+GENSEQ with code that gets auto vectorised with intel compiler (version 15.0 and above)
  File "/home/mudalige/OP2-GIT/OP2-Common/translator/c/python/op2_gen_mpi_vec.py", line 203, in op2_gen_mpi_vec
    % name, nargs
TypeError: not enough arguments for format string

**Comment by aowenson** [comment]
That particular error is fixed. But there is an underlying error in the interaction between aero and the vec translator that precedes this branch. I have restored its original fix: comment out the call to vec translation.

**Comment by gihanmudalige** [comment]
Tests all passed. @reguly  could you approve ?

**Pull request merged**
