### PR TITLE
Feature/makefile improvements

### PR DESCRIPTION
**Pull request by aowenson**
The main change is to remove the reliance on \<X\>_INSTALL_PATH variables being set, regardless of if the user has made changes to the PATH, CPATH and LD_LIBRARY_PATH env vars that allow binaries and libraries to be located.

And specifically for MPI_INSTALL_PATH, I have made some additional changes that allow for it being set to "$I_MPI_ROOT", rather than "$I_MPI_ROOT/intel64" as was required by the previous Makefile.

Thoughts?

### CODE REVIEW

**Comment by aowenson** [comment]
Also, I have not updated all Makefiles in the project to follow this style, just OP2-C and Airfoil-HDF5-C. I thought it best to have these changes approved before updating all Makefiles.

**Comment by reguly** [comment]
Thanks - looks good! At some point I'll pull all the common stuff into some common Makefiles...

**Comment by gihanmudalige** [comment]
Before merging .. could we modify all applications please. Ideally including the Fortran applications.

**Comment by aowenson** [comment]
Agreed, although I will not be able to update the remaining Makefiles any time soon.

**Comment by gihanmudalige** [comment]
@aowenson No problem. I would rather we change the whole set of Makefiles at once rather than forgetting to do them.

**Comment by aowenson** [comment]
I have ported these changes to all other Makefiles.

**Comment by reguly** [comment]
Thank you Andrew! Looks good to me - @gihanmudalige please run the usual tests.

**Comment by gihanmudalige** [comment]
@aowenson Thanks for this. Did you update the Fortran apps and back-end Makefiles as well ? If so I think this is ok to be merged.

**Comment by aowenson** [comment]
I updated each file named "Makefile", including for the Fortran codes.

**Comment by gihanmudalige** [comment]
@aowenson , excellent. As the tests go through without issue, I will merge this.

**Pull request merged**
