### PR TITLE
Feature/timing enhanced

### PR DESCRIPTION
**Pull request by reguly**
per-thread timing.

Looks good, however, @aowenson why do we need to expose all the MPI comm_size and comm_rank stuff to the user?

### CODE REVIEW

**Comment by aowenson** [comment]
They do not need to be exposed to the user, but they are needed by op_timing_output_2_csv() in order to output the times of each process (as well as each thread) to a single file, and to do so one at a time. The files that contain the implementations of op_mpi_comm_rank() and op_mpi_comm_size() seemed sensible choices.

**Comment by reguly** [comment]
a few minor things:
- we already have a routine which computes mean and variance (op_compute_moment)
- for timing, please use ops_timers, don't create another API
- you only use the custom comm_rank, comm_size and max_num_threads calls in op_lib_core.c, please move their declarations in there so they are not exposed

**Comment by reguly** [comment]
Looks good! @gihanmudalige please run the usual tests

**Comment by aowenson** [comment]
Not just yet Gihan, one further commit is planned to address Istvan's third remark.

**Comment by gihanmudalige** [comment]
Ok will do.

**Comment by aowenson** [comment]
I have finished cleaning up. The only remaining declaration that I cannot move into op_lib_core.c is get_num_threads_per_process(), as its implementation depends on whether OpenMP is being used (and compilation of op_lib_core.c cannot know this).

**Comment by gihanmudalige** [comment]
I will do the tests runs. 
@reguly could you confirm that these new features are acceptable. Given the recent developments related to releases, we need to be more strict in accepting commits to the master. A further requirement is to add the necessary documentation to the user documentation.

**Comment by gihanmudalige** [comment]
I am gettgin errors in -- Building Airfoil Plain DP with Intel Compilers

/opt/compilers/intel/intelPS-2015/impi_latest/intel64//bin/mpicxx -O3 -xHost -DMPICH_IGNORE_CXX_SEEK -restrict -fno-alias -inline-forceinline -qopt-report -parallel -DVECTORIZE  airfoil_mpi_op.cpp cuda/airfoil_kernels_mpi_cu.o \
		  -I/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/include -I/opt/parmetis-intel//include -DHAVE_PARMETIS -DPARMETIS_VER_4 -I/opt/ptscotch-intel//include -DHAVE_PTSCOTCH \
		  -L/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/lib -lop2_mpi_cuda -L/opt/parmetis-intel//lib -lparmetis -lmetis -L/opt/ptscotch-intel//lib/ -lptscotch -L/opt/ptscotch-intel//lib/ -lptscotcherr \
		  -L/usr/local/cuda/lib64 -lcudart -o airfoil_mpi_cuda
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/lib/libop2_mpi_cuda.a(op_mpi_core.o): In function `op_compute_moment_across_threads':
src/mpi/op_mpi_core.c:(.text+0xa791): undefined reference to `get_num_threads_per_process'
/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/lib/libop2_mpi_cuda.a(op_lib_core.o): In function `op_timing_output_core':
src/core/op_lib_core.c:(.text+0x1b25): undefined reference to `get_num_threads_per_process'
/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/lib/libop2_mpi_cuda.a(op_lib_core.o): In function `op_timing_output_2_file':
src/core/op_lib_core.c:(.text+0x1f8e): undefined reference to `get_num_threads_per_process'
/home/mgiles/mudalige/OP2-GIT/OP2-Common/op2//c/lib/libop2_mpi_cuda.a(op_lib_core.o): In function `op_timing_realloc':
src/core/op_lib_core.c:(.text+0x234c): undefined reference to `get_num_threads_per_process'
make: *** [airfoil_mpi_cuda] Error 1

**Comment by aowenson** [comment]
Fixed.

**Comment by gihanmudalige** [comment]
@aowenson  could you check ./airfoil_mpi_openmp  in Airfoil Plain DP built with Intel Compilers. I am getting :
*** Error in `./airfoil_mpi_openmp': corrupted double-linked list: 0x000000000101c710 ***

**Comment by gihanmudalige** [comment]
OK the tests all pass. 
@aowenson is these features important for your paper ? or can we review this a bit later before approving the merge ?

**Comment by gihanmudalige** [comment]
I am reviewing this branch.  @aowenson Can you summarise any new API calls added in this branch (so we can add it to the docs). 
Additionally you note that get_num_threads_per_process() cannot be placed in op_lib_core.c. Is there a way to do this using #ifdef _OPENMP   ?

**Comment by aowenson** [comment]
The API has three new methods, although only the first is expected to be used by users:
- `void op_timings_to_csv(const char *)` - declared in op_lib_core.h, defined in the backends
- `void op_timing_realloc_manytime(int kernel, int num_timers)` - declared and defined in op_lib_core
-` void op_compute_moment_across_times(double* times, int ntimes, bool ignore_zeros, double *first, double *second)` - declared and defined in op_lib_core

I have added an entry into the documentation for this.

The issue with get_num_threads_per_process() in op_lib_core.c is resolved, it no longer has dependencies on the targeted backend.

**Comment by gihanmudalige** [comment]
What happens for MPI + OPENMP executions ? Does setting OP_TIME_THREADS then give a breakdown for MPI procs as well as thrads for each MPI proc ?

**Comment by aowenson** [comment]
It will give a breakdown for each thread of each rank. Eg, for 2 ranks each with 2 threads:

rank, thread,...
0, 0, ...
0, 1, ...
1, 0, ...
1, 1, ...

**Comment by gihanmudalige** [comment]
Ok. Great. let me add some details about this to the doc.

**Comment by gihanmudalige** [comment]
I am getting the following error :

clang-4.0: warning: argument unused during compilation: '-L/opt/hdf5-gnu/lib' [-Wunused-command-line-argument]
In file included from openmp4/aero_omp4kernel_funcs.cpp:79:
In file included from openmp4/res_calc_omp4kernel_func.cpp:5:
openmp4/../res_calc.h:14:19: error: use of undeclared identifier 'Ng2_xi'
      det_x_xi += Ng2_xi[4 * i + 16 + m] * x[m][1];
                  ^
openmp4/../res_calc.h:16:27: error: use of undeclared identifier 'Ng2_xi'
      N_x[m] = det_x_xi * Ng2_xi[4 * i + m];
                          ^
openmp4/../res_calc.h:20:12: error: use of undeclared identifier 'Ng2_xi'

**Pull request merged**
