### PR TITLE
re-order const declaration and includes

### PR DESCRIPTION
**Pull request by basegpu**
As described [here](https://github.com/OP-DSL/OP2-Common/issues/133), user defined includes are put in separate header file.

Although, inside the includes we referred to the global constants. Therefore we had to put the const declarations before the includes for all backends. I don't think that it will have other unexpected impacts, right?

### CODE REVIEW

**Comment by basegpu** [comment]
I'll take care of these conflicts and will commit again...

**Comment by basegpu** [comment]
conflicts resolved.

**Comment by basegpu** [comment]
Is there anything I can do to proceed with merging? Or has the re-ordering an unexpected impact on any of the backends libs?

**Comment by gihanmudalige** [comment]
Hi Samuel .. I am attempting to test this branch. Will approve soon.

**Comment by gihanmudalige** [comment]
This is OK to be merged now.

**Comment by basegpu** [comment]
many thx for this!

**Pull request merged**
